name: Docker Build and Push with SemVer

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggers

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Determine new version using SemVer
      - name: Determine SemVer
        id: semver
        uses: actions/semver-release@v1
        with:
          # Default to increment the patch version
          increment: patch
          major-label: major
          minor-label: minor
          patch-label: patch

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            joshuafullerdocker/adsbxcot-deploy:latest
            joshuafullerdocker/adsbxcot-deploy:${{ steps.semver.outputs.new_version }}

      # Step 5: Commit new version to repository
      - name: Push new version tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a ${{ steps.semver.outputs.new_version }} -m "Release version ${{ steps.semver.outputs.new_version }}"
          git push origin ${{ steps.semver.outputs.new_version }}
