name: Build & Release Docker Image (with SemVer)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # IMPORTANT: Specify the environment name exactly as it appears in your repo settings
    environment: "Production"  # <-- or "Staging", "Test", etc.

    steps:
      # 1. Check out code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Determine next SemVer version
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          # if you’re enforcing conventional commits
          conventionalCommits: true
          failOnNoBump: true

      # 3. Log in to Docker Hub using environment secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # environment secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # environment secret

      # 4. Build & push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            joshuafullerdocker/adsbxcot-deploy:latest
            joshuafullerdocker/adsbxcot-deploy:${{ steps.semver.outputs.next }}

      # 5. Tag repo with next version
      - name: Tag repo with next version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a ${{ steps.semver.outputs.next }} -m "Release version ${{ steps.semver.outputs.next }}"
          git push origin ${{ steps.semver.outputs.next }}

      # 6. Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.semver.outputs.next }}
          release_name: "Release ${{ steps.semver.outputs.next }}"
          body: "Automated release for version ${{ steps.semver.outputs.next }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
