name: Build & Release Docker Image (with SemVer)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # Use the 'Production' environment so environment-level secrets/variables are available
    environment: "Production"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          conventionalCommits: true
          failOnNoBump: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # DockerHub username is stored as a variable
          username: ${{ vars.DOCKERHUB_USERNAME }}
          # DockerHub token is stored as a secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            joshuafullerdocker/adsbxcot-deploy:latest
            joshuafullerdocker/adsbxcot-deploy:${{ steps.semver.outputs.next }}

      - name: Tag repo with next version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a ${{ steps.semver.outputs.next }} -m "Release version ${{ steps.semver.outputs.next }}"
          git push origin ${{ steps.semver.outputs.next }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.semver.outputs.next }}
          release_name: "Release ${{ steps.semver.outputs.next }}"
          body: "Automated release for version ${{ steps.semver.outputs.next }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
