name: Build & Release Docker Image (with SemVer)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Determine next SemVer version based on existing tags
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          noVersionBumpBehavior: patch

      # 3. Log in to Docker Hub (using your secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build & push Docker image (two tags: latest & the semver number)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            joshuafullerdocker/adsbxcot-deploy:latest
            joshuafullerdocker/adsbxcot-deploy:${{ steps.semver.outputs.next }}

      # 5. Push a git tag to the repo, matching the new version
      - name: Tag repo with next version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a ${{ steps.semver.outputs.next }} -m "Release version ${{ steps.semver.outputs.next }}"
          git push origin ${{ steps.semver.outputs.next }}

      # 6. Create a GitHub Release for the new version
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.semver.outputs.next }}
          release_name: "Release ${{ steps.semver.outputs.next }}"
          body: "Automated release for version ${{ steps.semver.outputs.next }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
